name: Linter
on: [pull_request]
jobs:
  linter:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run linter
        uses: ricardochaves/python-lint@v1.3.0              
        with:
          use-pylint: true
          python-root-list: src/model src/console src/gui
          
